# Generated by Django 3.0.4 on 2020-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0004_auto_20200415_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(
                default='https://preview.redd.it/cqxp2xypqo941.jpg?auto=webp&s=f1475a3fa74d38c239550f77718e6eefd1269dfb',
                upload_to='company_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(
                default='https://preview.redd.it/cqxp2xypqo941.jpg?auto=webp&s=f1475a3fa74d38c239550f77718e6eefd1269dfb',
                upload_to='speciality_images'),
            preserve_default=False,
        ),
    ]
