# Generated by Django 3.0.4 on 2020-04-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0001_initial'),
        ('accounts', '0003_auto_20200412_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('written_cover_letter', models.CharField(max_length=256)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='applications', to='jobs.Vacancy')),
            ],
        ),
    ]
