# Generated by Django 3.0.4 on 2020-04-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0002_auto_20200415_1851'),
        ('accounts', '0004_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='surname',
        ),
        migrations.AddField(
            model_name='resume',
            name='owner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='resume', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='applications', to='jobs.Vacancy'),
        ),
    ]
