# Generated by Django 3.0.4 on 2020-04-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200415_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
